version: "3.1"

services:
    apache:
        build: './docker/apache'
        ports:
            - "9800:80"
        volumes:
            - '.:/usr/local/apache2/htdocs'
        depends_on:
            - php

    php:
        build: './docker/php'
